/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;
import Classes.*;
import Modelos.*;
import Util.*;
import Telas.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author u18300
 */
public class TelaInicial extends javax.swing.JFrame {
    BDConexao c = new BDConexao();
    reclamacoesModeloDeTabela eModelFicha;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() throws SQLException, ClassNotFoundException {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE );
        populaTabelaFicha();
    }
    private void populaTabelaFicha(){
        tbtMostrar.removeAll();
        List<FichaReclamacao> fichas = new ArrayList<FichaReclamacao>();
        FichaReclamacao f = null;
        // Pega os dados do Banco de Dados
        try{
            Connection con = c.criaConexao();
            ResultSet dados =  CRUDTodos.PesquisarReclamacao(con);
            while (dados.next()){
                 f = new FichaReclamacao(dados.getInt("ficId"),
                                dados.getInt("ficCliId"),
                                dados.getString("ficTipo"),
                                dados.getString("ficDesc"),
                                dados.getDate("ficDataEmicao"));
                 fichas.add(f);
             }
             con.close();
         } 
        catch(ClassNotFoundException | SQLException e)
        {
            
        }
       // Cria o modelo e associa com o List
       eModelFicha = new reclamacoesModeloDeTabela(fichas);
       // Associa o modelo à tabela
       tbtMostrar.setModel(eModelFicha);
    }
    private void populaTabelaFicha(ResultSet rs){
        tbtMostrar.removeAll();
        List<FichaReclamacao> fichas = new ArrayList<FichaReclamacao>();
        FichaReclamacao f = null;
        // Pega os dados do Banco de Dados
        try{
            Connection con = c.criaConexao();
            ResultSet dados =  rs;
            while (dados.next()){
                 f = new FichaReclamacao(dados.getInt("ficId"),
                                dados.getInt("ficCliId"),
                                dados.getString("ficTipo"),
                                dados.getString("ficDesc"),
                                dados.getDate("ficDataEmicao"));
                 fichas.add(f);
             }
             con.close();
         } 
        catch(ClassNotFoundException | SQLException e)
        {
            
        }
       // Cria o modelo e associa com o List
       eModelFicha = new reclamacoesModeloDeTabela(fichas);
       // Associa o modelo à tabela
       tbtMostrar.setModel(eModelFicha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtMostrar = new javax.swing.JTable();
        btnAbrirReclamacao = new javax.swing.JButton();
        btnExibirReclamacao = new javax.swing.JButton();
        btnExibirPareto = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisarReclamacaoPorCPF = new javax.swing.JButton();
        btnDeletarReclamacao = new javax.swing.JButton();
        btnPesquisarReclamacaoPorTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel1.setText("TELA ADMINISTRATIVA");

        tbtMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbtMostrar);

        btnAbrirReclamacao.setText("ABRIR RECLAMAÇÃO");
        btnAbrirReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirReclamacaoActionPerformed(evt);
            }
        });

        btnExibirReclamacao.setText("EXIBIR RECLAMAÇÃO");
        btnExibirReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirReclamacaoActionPerformed(evt);
            }
        });

        btnExibirPareto.setText("EXIBIR GRÁFICO DE PARETO");
        btnExibirPareto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirParetoActionPerformed(evt);
            }
        });

        btnProdutos.setText("PRODUTOS");
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnPesquisarReclamacaoPorCPF.setText("Pesquisar por CPF");
        btnPesquisarReclamacaoPorCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarReclamacaoPorCPFActionPerformed(evt);
            }
        });

        btnDeletarReclamacao.setText("Deletar");
        btnDeletarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarReclamacaoActionPerformed(evt);
            }
        });

        btnPesquisarReclamacaoPorTipo.setText("Pesquisar por Tipo");
        btnPesquisarReclamacaoPorTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarReclamacaoPorTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAbrirReclamacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExibirReclamacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExibirPareto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPesquisarReclamacaoPorCPF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPesquisarReclamacaoPorTipo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeletarReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarReclamacaoPorCPF)
                    .addComponent(btnDeletarReclamacao)
                    .addComponent(btnPesquisarReclamacaoPorTipo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrirReclamacao)
                    .addComponent(btnExibirReclamacao)
                    .addComponent(btnExibirPareto)
                    .addComponent(btnProdutos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirParetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirParetoActionPerformed
        // TODO add your handling code here:
        /**
         * CRIAÇÃO DO GRÁFICO DE PARETO
         */
        final GraficoPareto demo;
        try {
            demo = new GraficoPareto("GRÁFICO DE PARETO");
            demo.pack();
            RefineryUtilities.centerFrameOnScreen(demo);
            demo.setVisible(true);
            demo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExibirParetoActionPerformed

    private void btnAbrirReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirReclamacaoActionPerformed
        // TODO add your handling code here:
        /**
         * CRIAR NOVA RECLAMAÇÃO
         */
        TelaAbrirReclamacao telaR = new TelaAbrirReclamacao();
        telaR.setVisible(true);
    }//GEN-LAST:event_btnAbrirReclamacaoActionPerformed

    private void btnExibirReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirReclamacaoActionPerformed
        // TODO add your handling code here:
        /**
         * EXIBIR RECLAMAÇÃO
         */
        try {
            ExibirReclamacao telaR = new ExibirReclamacao();
            telaR.setId(Integer.parseInt(tbtMostrar.getModel().getValueAt(tbtMostrar.getSelectedRow(), 0).toString()));
            telaR.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExibirReclamacaoActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        try {
            Produtos telaProd;
            telaProd = new Produtos();
             telaProd.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnDeletarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarReclamacaoActionPerformed
        // TODO add your handling code here:
        //Integer.parseInt(tbtProdutos.getModel().getValueAt(tbtProdutos.getSelectedRow(), 0).toString()), con
        try {
            Connection con = c.criaConexao();
            CRUDTodos.DeletarReclamacao(Integer.parseInt(tbtMostrar.getModel().getValueAt(tbtMostrar.getSelectedRow(), 0).toString()), con);
            populaTabelaFicha();
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDeletarReclamacaoActionPerformed

    private void btnPesquisarReclamacaoPorCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarReclamacaoPorCPFActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = c.criaConexao();
            ResultSet rs = CRUDTodos.PesquisarClientePorCPF(Integer.parseInt(txtPesquisar.getText()), con);
            rs.next();
            populaTabelaFicha(CRUDTodos.PesquisarReclamacaoPorCliente(rs.getInt("cliId"), con));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPesquisarReclamacaoPorCPFActionPerformed

    private void btnPesquisarReclamacaoPorTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarReclamacaoPorTipoActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = c.criaConexao();
            populaTabelaFicha(CRUDTodos.PesquisarReclamacaoPorTipo(txtPesquisar.getText(), con));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarReclamacaoPorTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaInicial().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirReclamacao;
    private javax.swing.JButton btnDeletarReclamacao;
    private javax.swing.JButton btnExibirPareto;
    private javax.swing.JButton btnExibirReclamacao;
    private javax.swing.JButton btnPesquisarReclamacaoPorCPF;
    private javax.swing.JButton btnPesquisarReclamacaoPorTipo;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtMostrar;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
