/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.FichaReclamacao;
import Util.BDConexao;
import Util.CRUDTodos;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextArea;


/**
 *
 * @author u18300
 */
public class ExibirReclamacao extends javax.swing.JFrame {
    private int id =0;
    BDConexao c = new BDConexao();
    /**
     * Creates new form ExibirReclamacao2
     */
    public ExibirReclamacao() {
        initComponents();
        cbx_causas.removeAll();
        
        //MOTIVO DE NÃO TER ACEITO
        txtReclamacao_MotivoNaoAceita.setEnabled(false);
        txtReclamacao_ResponsavelNaoAceitar.setEnabled(false);
        
        //APURAÇÃO DA RECLAMAÇÃO
        txtNovaCausa.setEnabled(false);
        txtReclamacao_CorrecaoAceitado.setEnabled(false);
        txtReclamacao_DataCorrecao.setEnabled(false);
        txtReclamacao_ResponsavelAnalise.setEnabled(false);
        cbx_causas.setEnabled(false);
        //CONFIRMAÇÃO DE CONCLUSAO
        txtReclamacao_ResponsavelConcluido.setEnabled(false);
        btnRRelatarCorrecao.setEnabled(false);
        btnRConfirmarConclusao.setEnabled(false);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    public void setId(int id) throws SQLException, ClassNotFoundException
    {
        this.id = id;
        try {
            popularFicha();
            popularCausas();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ExibirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtReclamacao_ResponsavelNaoAceitar = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtReclamacao_CorrecaoAceitado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtReclamacao_DataCorrecao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        txtReclamacao_ResponsavelAnalise = new javax.swing.JTextField();
        lblDataReclamacao = new javax.swing.JLabel();
        btnRRelatarCorrecao = new javax.swing.JButton();
        lblAreaReclamacao = new javax.swing.JLabel();
        btnRConfirmarConclusao = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblReclamacao_DataConcluido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaneMensagem = new javax.swing.JTextPane();
        txtReclamacao_ResponsavelConcluido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRAceitarReclamacao = new javax.swing.JButton();
        btnRNegarReclamacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtReclamacao_MotivoNaoAceita = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnReclamacao_ExibirNota = new javax.swing.JButton();
        cbx_causas = new javax.swing.JComboBox<>();
        txtNovaCausa = new javax.swing.JTextField();
        btnReclamacao_ConsultarGarantia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Responsável:");

        jLabel4.setText("Causa apuradas:");

        jLabel6.setText("Correções:");

        jLabel7.setText("Data Prevista de correção:");

        jLabel9.setText("Resposável");

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        lblDataReclamacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataReclamacao.setText("Data da Reclamação:");

        btnRRelatarCorrecao.setText("Relatar");
        btnRRelatarCorrecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRRelatarCorrecaoActionPerformed(evt);
            }
        });

        lblAreaReclamacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAreaReclamacao.setText("Área da Reclamação:");

        btnRConfirmarConclusao.setText("Confirmar Conclusão");
        btnRConfirmarConclusao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRConfirmarConclusaoActionPerformed(evt);
            }
        });

        lblReclamacao_DataConcluido.setText("Data:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Mensagem:");

        jLabel10.setText("Concluido por:");

        jScrollPane1.setViewportView(txtPaneMensagem);

        btnRAceitarReclamacao.setText("Aceito");
        btnRAceitarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAceitarReclamacaoActionPerformed(evt);
            }
        });

        btnRNegarReclamacao.setText("Não aceito");
        btnRNegarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRNegarReclamacaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("RECLAMAÇÃO");

        jLabel2.setText("Motivo (caso) da não aceitação :");

        btnReclamacao_ExibirNota.setText("Exibir Nota Fiscal");
        btnReclamacao_ExibirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReclamacao_ExibirNotaActionPerformed(evt);
            }
        });

        cbx_causas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_causas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_causasItemStateChanged(evt);
            }
        });

        btnReclamacao_ConsultarGarantia.setText("Consultar lista de garantia");
        btnReclamacao_ConsultarGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReclamacao_ConsultarGarantiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliente)
                    .addComponent(lblDataReclamacao))
                .addGap(178, 411, Short.MAX_VALUE)
                .addComponent(lblAreaReclamacao)
                .addGap(222, 222, 222))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReclamacao_MotivoNaoAceita)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRAceitarReclamacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRNegarReclamacao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(96, 96, 96)
                        .addComponent(txtReclamacao_ResponsavelNaoAceitar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnRRelatarCorrecao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRConfirmarConclusao)
                        .addGap(18, 18, 18)
                        .addComponent(lblReclamacao_DataConcluido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReclamacao_ResponsavelConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReclamacao_DataCorrecao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReclamacao_ResponsavelAnalise)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbx_causas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNovaCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtReclamacao_CorrecaoAceitado))
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReclamacao_ExibirNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReclamacao_ConsultarGarantia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataReclamacao)
                    .addComponent(lblAreaReclamacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReclamacao_ExibirNota)
                    .addComponent(btnReclamacao_ConsultarGarantia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRAceitarReclamacao)
                    .addComponent(btnRNegarReclamacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReclamacao_MotivoNaoAceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtReclamacao_ResponsavelNaoAceitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbx_causas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNovaCausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtReclamacao_CorrecaoAceitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtReclamacao_DataCorrecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtReclamacao_ResponsavelAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtReclamacao_ResponsavelConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRRelatarCorrecao)
                        .addComponent(btnRConfirmarConclusao)
                        .addComponent(lblReclamacao_DataConcluido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_causasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_causasItemStateChanged
        // TODO add your handling code here:
        if (cbx_causas.getSelectedItem() == "Outro")
            txtNovaCausa.setEnabled(true);
    }//GEN-LAST:event_cbx_causasItemStateChanged

    private void btnReclamacao_ExibirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReclamacao_ExibirNotaActionPerformed
        // TODO add your handling code here:
        if (Desktop.isDesktopSupported()) {
            try {
            Connection conn = c.criaConexao();
            File myFile = new File(CRUDTodos.getPDFData(id, conn));
            Desktop.getDesktop().open(myFile);
            conn.close();
            }
             catch (SQLException | ClassNotFoundException | IOException ex) {
                Logger.getLogger(ExibirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
            }
}

    }//GEN-LAST:event_btnReclamacao_ExibirNotaActionPerformed

    private void btnRNegarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRNegarReclamacaoActionPerformed
        // TODO add your handling code here:
        txtReclamacao_MotivoNaoAceita.setEnabled(true);
        txtReclamacao_ResponsavelNaoAceitar.setEnabled(true);
        btnRAceitarReclamacao.setEnabled(false);
        btnRRelatarCorrecao.setEnabled(true);
    }//GEN-LAST:event_btnRNegarReclamacaoActionPerformed

    private void btnRAceitarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAceitarReclamacaoActionPerformed
        // TODO add your handling code here:
        cbx_causas.setEnabled(true);
        txtReclamacao_CorrecaoAceitado.setEnabled(true);
        txtReclamacao_DataCorrecao.setEnabled(true);
        txtReclamacao_ResponsavelAnalise.setEnabled(true);
        btnRRelatarCorrecao.setEnabled(true);
        btnRNegarReclamacao.setEnabled(false);
    }//GEN-LAST:event_btnRAceitarReclamacaoActionPerformed

    private void btnRRelatarCorrecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRRelatarCorrecaoActionPerformed
        // TODO add your handling code here:
        try{
        Connection con = c.criaConexao();
        //public FichaReclamacao(int FichaCodigo, String motivoNaceita, String FunNAceito) {
        if (txtReclamacao_MotivoNaoAceita.getText().length()>0)
            CRUDTodos.AlterarReclamacaoNAceito(new FichaReclamacao(id,txtReclamacao_MotivoNaoAceita.getText(),txtReclamacao_ResponsavelNaoAceitar.getText()), con);
        else
        {
            ResultSet rs = CRUDTodos.getCausas(cbx_causas.getSelectedItem().toString(), con);
            rs.next();
            //public FichaReclamacao(int FichaCodigo, Date dataPrevista, String funcPrevista, int causaId, String correcao) {
            CRUDTodos.AlterarReclamacaoPermitida(new FichaReclamacao(id,formatarData(txtReclamacao_DataCorrecao.getText()),txtReclamacao_ResponsavelAnalise.getText()
            ,rs.getInt("cauId"),txtReclamacao_CorrecaoAceitado.getText()), con);
        }
        } catch (Exception ex) {
            Logger.getLogger(ExibirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnRConfirmarConclusao.setEnabled(true);
        txtReclamacao_ResponsavelConcluido.setEnabled(true);
    }//GEN-LAST:event_btnRRelatarCorrecaoActionPerformed

    private void btnRConfirmarConclusaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRConfirmarConclusaoActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = c.criaConexao();
            java.util.Date data = new java.util.Date();
            java.sql.Date dataSql = new java.sql.Date(data.toInstant().getEpochSecond());
            lblReclamacao_DataConcluido.setText("Data: "+data.toString());
            //public FichaReclamacao(int FichaCodigo, Date dataConcluido, String funcConcluido) {
            CRUDTodos.AlterarReclamacaoConcluida(new FichaReclamacao(id,dataSql,txtReclamacao_ResponsavelConcluido.getText()), con);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ExibirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRConfirmarConclusaoActionPerformed

    private void btnReclamacao_ConsultarGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReclamacao_ConsultarGarantiaActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = c.criaConexao();
            ResultSet rs = CRUDTodos.PesquisarProduto(con);
            String result="";
            while (rs.next())
            {
                result+=rs.getString("prodNome")+" - tempo de garantia: "+rs.getString("prodGarantia")+"\n";
            }
            JFrame frame = new JFrame();
            JTextArea area = new JTextArea(result);
            
            area.setEditable(false);
            area.setFont(new Font(Font.SERIF, Font.BOLD, 30));
            
            frame.add(area);
            frame.setSize(new Dimension(1000, 1000));
            frame.setVisible(true);
            frame.setDefaultCloseOperation(HIDE_ON_CLOSE);
        } catch (Exception ex) {
            Logger.getLogger(ExibirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnReclamacao_ConsultarGarantiaActionPerformed

    public void popularFicha() throws SQLException, ClassNotFoundException
    {
        Connection con = c.criaConexao();
        ResultSet rs = CRUDTodos.PesquisarReclamacaoPorID(this.id,con);
        rs.next();
        System.out.println(rs.isBeforeFirst());
        System.out.println(rs.getInt("ficCliId"));
        ResultSet cli = CRUDTodos.PesquisarClientePorId(rs.getInt("ficCliId"), con);
        cli.next();
        txtPaneMensagem.setText(rs.getString("ficDesc"));
        lblCliente.setText("Cliente: nome:" + cli.getString("cliNome")+" cpf:" + cli.getInt("cliCPF"));
        lblDataReclamacao.setText("Data da Reclamação: "+rs.getDate("ficDataEmicao"));
        lblAreaReclamacao.setText("Área da Reclamação: "+rs.getString("ficTipo"));
        con.close();
    }
    
    public Date formatarData(String data) throws Exception 
    { 
    if (data == null || data.equals(""))
        return null;
    Date date = null;
    try {
    DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    date = (Date)(java.util.Date)formatter.parse(data);
    } 
    catch (ParseException e) { 
    throw e;
    }
    return date;
}
    
    public void popularCausas() throws SQLException, ClassNotFoundException
    {
        cbx_causas.removeAllItems();
        Connection con = c.criaConexao();
        ResultSet rs = CRUDTodos.getCausas(con);
        while(rs.next())
            cbx_causas.addItem(rs.getString("cauCausa"));
        con.close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new ExibirReclamacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRAceitarReclamacao;
    private javax.swing.JButton btnRConfirmarConclusao;
    private javax.swing.JButton btnRNegarReclamacao;
    private javax.swing.JButton btnRRelatarCorrecao;
    private javax.swing.JButton btnReclamacao_ConsultarGarantia;
    private javax.swing.JButton btnReclamacao_ExibirNota;
    private javax.swing.JComboBox<String> cbx_causas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAreaReclamacao;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDataReclamacao;
    private javax.swing.JLabel lblReclamacao_DataConcluido;
    private javax.swing.JTextField txtNovaCausa;
    private javax.swing.JTextPane txtPaneMensagem;
    private javax.swing.JTextField txtReclamacao_CorrecaoAceitado;
    private javax.swing.JTextField txtReclamacao_DataCorrecao;
    private javax.swing.JTextField txtReclamacao_MotivoNaoAceita;
    private javax.swing.JTextField txtReclamacao_ResponsavelAnalise;
    private javax.swing.JTextField txtReclamacao_ResponsavelConcluido;
    private javax.swing.JTextField txtReclamacao_ResponsavelNaoAceitar;
    // End of variables declaration//GEN-END:variables
}
