/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.Cliente;
import Classes.FichaReclamacao;
import Modelos.clienteModeloDeTabela;
import Util.BDConexao;
import Util.CRUDTodos;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author 00
 */
public class TelaAbrirReclamacao extends javax.swing.JFrame {
    BDConexao c = new BDConexao();
    int cpfSelected;
    clienteModeloDeTabela eModelCliente;
    int uniqueID;
    /**
     * Creates new form TelaAbrirReclamacao2
     */
    public TelaAbrirReclamacao() {
        this.cpfSelected = Integer.parseInt(tbtCliente.getModel().getValueAt(tbtCliente.getSelectedRow(),0).toString());
        initComponents();
        pack();
        setLocationRelativeTo(null);
        txtAreaReclamacao.setEnabled(false);
        cbx_areaReclamacao.removeAllItems();
        cbx_areaReclamacao.addItem("Atendimento");
        cbx_areaReclamacao.addItem("Logística");
        cbx_areaReclamacao.addItem("Prazo de reparação");
        cbx_areaReclamacao.addItem("Avaria");
        cbx_areaReclamacao.addItem("Outro");
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
        tbtCliente.removeAll();
    }
    private void populaTabelaProduto() throws SQLException, ClassNotFoundException{
        tbtCliente.removeAll();
        List<Cliente> clientes = new ArrayList<Cliente>();
        Cliente f = null;
        // Pega os dados do Banco de Dados
        // public Cliente(String nome, String email, String cep, String endereco, String cidade, String senha,String cpf,int telefone) {
        try{
            Connection con = c.criaConexao();
            ResultSet dados =  CRUDTodos.PesquisarReclamacao(con);
            while (dados.next()){
                 f = new Cliente(dados.getString("cliNome"),dados.getString("cliEmail"),dados.getString("cliCEP"),dados.getString("cliAddress"),dados.getString("cliCidade"),
                         dados.getString("cliPsw"),dados.getString("cliCPF"),dados.getInt("cliTel"));
                 clientes.add(f);
             }
             con.close();
         } 
        catch(SQLException e)
        {}
       // Cria o modelo e associa com o List
       eModelCliente = new clienteModeloDeTabela(clientes);
       // Associa o modelo à tabela
       tbtCliente.setModel(eModelCliente);
    }
    private void populaTabelaProduto(ResultSet rs) throws SQLException, ClassNotFoundException{
        tbtCliente.removeAll();
        List<Cliente> clientes = new ArrayList<Cliente>();
        Cliente f = null;
        // Pega os dados do Banco de Dados
        // public Cliente(String nome, String email, String cep, String endereco, String cidade, String senha,String cpf,int telefone) {
        try{
            ResultSet dados =  rs;
            while (dados.next()){
                 f = new Cliente(dados.getString("cliNome"),dados.getString("cliEmail"),dados.getString("cliCEP"),dados.getString("cliAddress"),dados.getString("cliCidade"),
                         dados.getString("cliPsw"),dados.getString("cliCPF"),dados.getInt("cliTel"));
                 clientes.add(f);
             }
         } 
        catch(SQLException e)
        {}
       // Cria o modelo e associa com o List
       eModelCliente = new clienteModeloDeTabela(clientes);
       // Associa o modelo à tabela
       tbtCliente.setModel(eModelCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtCliente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnAReclamcao_InserirNota = new javax.swing.JButton();
        txtPesquisarCliente = new javax.swing.JTextField();
        btnAReclamcao_Enviar = new javax.swing.JButton();
        btnAReclamcao_PesquisarCli = new javax.swing.JButton();
        btnAReclamcao_CadastrarCli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtFuncionario = new javax.swing.JTextField();
        cbx_areaReclamacao = new javax.swing.JComboBox<>();
        txtAreaReclamacao = new javax.swing.JTextField();
        btnAReclamcao_ExcluirCli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbtCliente);

        txtMensagem.setColumns(20);
        txtMensagem.setRows(5);
        jScrollPane2.setViewportView(txtMensagem);

        jLabel5.setText("Pesquisar cliente por CPF:");

        btnAReclamcao_InserirNota.setText("INSERIR NOTA FISCAL");
        btnAReclamcao_InserirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAReclamcao_InserirNotaActionPerformed(evt);
            }
        });

        btnAReclamcao_Enviar.setText("ENVIAR");
        btnAReclamcao_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAReclamcao_EnviarActionPerformed(evt);
            }
        });

        btnAReclamcao_PesquisarCli.setText("PESQUISAR");

        btnAReclamcao_CadastrarCli.setText("CADASTRAR");
        btnAReclamcao_CadastrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAReclamcao_CadastrarCliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("FORMULÁRIO DE RECLAMAÇÃO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Área de Reclamação:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Registrada por:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mensagem:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Reclamação:");

        cbx_areaReclamacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_areaReclamacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_areaReclamacaoItemStateChanged(evt);
            }
        });

        btnAReclamcao_ExcluirCli.setText("EXCLUIR");
        btnAReclamcao_ExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAReclamcao_ExcluirCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesquisarCliente))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnAReclamcao_PesquisarCli)
                                .addContainerGap(25, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAReclamcao_CadastrarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAReclamcao_ExcluirCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFuncionario)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbx_areaReclamacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAreaReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnAReclamcao_InserirNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAReclamcao_Enviar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAReclamcao_PesquisarCli))
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAReclamcao_ExcluirCli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnAReclamcao_CadastrarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbx_areaReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAReclamcao_InserirNota)
                    .addComponent(btnAReclamcao_Enviar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAReclamcao_CadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAReclamcao_CadastrarCliActionPerformed
        // TODO add your handling code here:
        NovoCliente cliente = new NovoCliente();
        cliente.setVisible(true);
        if(cliente.worked)
            try {
                populaTabelaProduto();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAReclamcao_CadastrarCliActionPerformed

    private void cbx_areaReclamacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_areaReclamacaoItemStateChanged
        // TODO add your handling code here:
        if (cbx_areaReclamacao.getSelectedItem() == "Outro")
        {
            txtAreaReclamacao.setEnabled(true);
        }
    }//GEN-LAST:event_cbx_areaReclamacaoItemStateChanged

    private void btnAReclamcao_InserirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAReclamcao_InserirNotaActionPerformed
        // TODO add your handling code here:
        try{
        String path;
        Connection conn = c.criaConexao();
        uniqueID = CRUDTodos.getIdAvailable(conn)+1;
        JFileChooser fileChooser = new JFileChooser();
        path = fileChooser.getSelectedFile().getAbsoluteFile().toString();
        CRUDTodos.insertPDF(uniqueID,path,conn);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAReclamcao_InserirNotaActionPerformed

    private void btnAReclamcao_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAReclamcao_EnviarActionPerformed
        // TODO add your handling code here:
        // public FichaReclamacao(int ClienteCodigo, String Tipo, String Descricao, Date dataEmicao ,int idArquivo) {
        String item;
        Connection con;
        try {
            con = c.criaConexao();
            if(cbx_areaReclamacao.getSelectedItem()!=null)
                item = cbx_areaReclamacao.getSelectedItem().toString();
            else if(cbx_areaReclamacao.getSelectedItem() == "Outro");
                item = txtAreaReclamacao.getText();
            
        java.util.Date data = new java.util.Date();
        java.sql.Date dataSql = new java.sql.Date(data.toInstant().getEpochSecond());
         
        CRUDTodos.InserirReclamacao(new FichaReclamacao(cpfSelected,item,txtMensagem.getText(),dataSql,uniqueID), con);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAReclamcao_EnviarActionPerformed

    private void btnAReclamcao_ExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAReclamcao_ExcluirCliActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection con = c.criaConexao();
            CRUDTodos.DeletarCliente(cpfSelected, con);
        } catch (Exception ex) {
            Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAReclamcao_ExcluirCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAbrirReclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAbrirReclamacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAReclamcao_CadastrarCli;
    private javax.swing.JButton btnAReclamcao_Enviar;
    private javax.swing.JButton btnAReclamcao_ExcluirCli;
    private javax.swing.JButton btnAReclamcao_InserirNota;
    private javax.swing.JButton btnAReclamcao_PesquisarCli;
    private javax.swing.JComboBox<String> cbx_areaReclamacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbtCliente;
    private javax.swing.JTextField txtAreaReclamacao;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextArea txtMensagem;
    private javax.swing.JTextField txtPesquisarCliente;
    // End of variables declaration//GEN-END:variables
}
